### ISSUE TITLE
[BUG]: Need help installing Recon

### ISSUE THREAD

**Issue by ludovicc** [databrickslabs/remorph#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

ReconcileError

### Current Behavior

Hello,

I'm trying to use Recon to validate our CDC pipeline which send data from MariaDB to Databricks with Unity. I have setup a foreign catalog to MariaDB since MySQL is not supported by Recon yet.
I'm now trying to configure Recon to work with this setup, but if fails with an error message not really useful:

databricks -p prod  labs remorph reconcile

Cannot find recon table configuration in existing `reconcile` installation. Please provide the configuration file
Error: exit status 1

My config:

reconcile.yml
```yaml
data_source: databricks
database_config:
  source_schema: sga
  target_catalog: prod_ca_regional
  target_schema: landing
metadata_config:
  catalog: prod_ca_regional
  schema: reconcile
  volume: reconcile_volume
report_type: all
secret_scope: p-cac-b05-dhubreg-kv-kvd
version: 1
```

recon_config_databricks_prod_ca_regional_all.json
```json
{
  "source_catalog": "mariadb_ca",
  "source_schema": "sga",
  "target_catalog": "prod_ca_regional",
  "target_schema": "landing",
  "tables": [...]
}
```

### Expected Behavior

An error message that provides the names of the expected configuration files.

### Operating System

macOS

### Version

latest via Databricks CLI
